CREATE TABLE IF NOT EXISTS public.may2021
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    departure timestamp without time zone,
    "return" timestamp without time zone,
    departure_station_id integer NOT NULL,
    departure_station_name character varying(100) NOT NULL ,
    return_station_id integer  NOT NULL ,
    return_station_name character varying(100) COLLATE pg_catalog."default",
    covered_distance double precision,
    duration integer,
    CONSTRAINT may2021_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.june
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    departure timestamp without time zone,
    "return" timestamp without time zone,
    departure_station_id integer  NOT NULL ,
    departure_station_name character varying(100) NOT NULL ,
    return_station_id integer  NOT NULL ,
    return_station_name character varying(100) ,
    covered_distance double precision,
    duration integer,
   CONSTRAINT june_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.may
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    departure timestamp without time zone,
    "return" timestamp without time zone,
    departure_station_id integer NOT NULL,
    departure_station_name character varying(100) NOT NULL ,
    return_station_id integer  NOT NULL ,
    return_station_name character varying(100) COLLATE pg_catalog."default",
    covered_distance double precision,
    duration integer,
    CONSTRAINT may_pkey PRIMARY KEY (id)
);


create table stations(
                         FID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         ID integer NOT NULL,
                         Nimi varchar(100),
                         Namn varchar(100),
                         Name varchar(100),
                         Osoite varchar(100),
                         Adress varchar(100),
                         Kaupunki varchar(100),
                         Stad varchar(100),
                         Operaattor varchar (100),
                         Kapasiteet integer,
                         x double precision,
                         y double precision,
                        CONSTRAINT stations PRIMARY KEY (FID)
);





